### ISSUE TITLE
Logo Dessign

### ISSUE THREAD

**Issue by nunojesus** [cornerman/sloth#11]
Hello since you have interest in a logo for you this project, I will try to make my best to create a design for it.

You said that: " Sloth it is about being lazy and letting the library do some repetitive work for you." 

Can you specify the project better? what kind of  library  and what kind of repetitive work does it do.

Greetings!

Nuno Jesus

**Comment by cornerman** [comment]
This library is about communication between a client and a server. For example, a website wants to get some information from the server. It makes a request to server and gets a response with the corresponding information.

Sloth allows you to define what kind of methods (or what information) you want serve to the client and how the communication between client and server takes place (e.g. in-memory, http calls or websocket calls). From this information, code is generated that lets you make requests to the server without writing boilerplate code on how to do that. You define this once and then just lazily hang out in the trees like a sloth :)

Does that make sense to you?

**Comment by nunojesus** [comment]
Hello, here are my design for Sloth, for the concept I create 3 hexagonal with library folder, that are connected between them, which represents repetitive work.

I hope you like, if not I can make other design.

Greetings!

Nuno Jesus

![sloth final](https://user-images.githubusercontent.com/34600369/41507682-99e56166-722f-11e8-9bc7-6d07c086fe83.png)

**Comment by cornerman** [comment]
@nunojesus Thank you very much for the design! I think the connected hexagons are an interesting idea :)

Out of curiosity and because I really like being lazy, I would love to see a design with a sloth animal. Would that be possible?

**Comment by cornerman** [comment]
I am going to close this one because there was no more activity. If you ever have time, please feel free to reopen.
