### ISSUE TITLE
ZIO not supported

### ISSUE THREAD

**Issue by somdoron** [cornerman/sloth#110]
Because ZIO has multiple type arguments and Sloth assumes the first one is the return type ZIO cannot work with sloth.

Actually replacing head with last in following would probably solve it:

https://github.com/cornerman/sloth/blob/master/sloth/src/main/scala/internal/Macros.scala#L116
https://github.com/cornerman/sloth/blob/master/sloth/src/main/scala/internal/Macros.scala#L116

**Comment by cornerman** [comment]
Good Point! You are right, it should be enough to just assume the return value in the last type argument - which is also more intuitive.

Can you please try this branch?
```
libraryDependencies += "com.github.cornerman.sloth" %%% "sloth" % "last-typearg-SNAPSHOT"
```

**Comment by cornerman** [comment]
@somdoron Were you able to try this out?
