### ISSUE TITLE
Expose request as additional parameter

### ISSUE THREAD

**Issue by ioleo** [cornerman/sloth#156]
I'd like to add authorization for some routes. The simplest form would be to have additional request parameter in my methods, allowing to access eg. cookie headers. Perhaps thats already possible?

**Comment by cornerman** [comment]
Thanks for opening this issue. For my use-cases I am normally going for `Kleisli` or in case of zio for the environment.

So the return type of your api methods in the server would become: `Kleisli[F, MyRequest, *]`. You can provide the myRequest where you are using the sloth Router. And then access it in your methods when needed.

Does that help?

**Comment by ioleo** [comment]
@cornerman yes, actually a bit silly I didn't think of environment (using zio) :D
