### ISSUE TITLE
Error in Router assignment

### ISSUE THREAD

**Issue by krishna444** [cornerman/sloth#16]
I get an error when I initialize router from the example provided in the ReadMe text:
` val router = Router[ByteBuffer, Future].route[MyApi](MyApiImpl)`

The error is:

**could not find implicit value for parameter functor: cats.Functor[scala.concurrent.Future]
not enough arguments for macro method route: (implicit functor: cats.Functor[scala.concurrent.Future])sloth.Router[java.nio.ByteBuffer,scala.concurrent.Future]. Unspecified value parameter functor.**

Because of this error, I could not compile it.

**Comment by cornerman** [comment]
Oh good point. I think the example is missing an import an ExecutionContext. This is needed to get a `Functor` instance for the `Future` type.

Does it work if you add `mport scala.concurrent.ExecutionContext.Implicits.global`? Or you have a method where you require `(implicit ec: ExecutionContext)`.

**Comment by krishna444** [comment]
Hi cornerman,

great to have your prompt answer. I just wanted to integrate your library because **"autowire library from lihaoyu"** did not work. 

Unfortunately I am still getting this error and could not go further. Please have a look at my sample code:

```
package com.kpaudel.ui
import sloth._
import boopickle.Default._
import chameleon.ext.boopickle._
import java.nio.ByteBuffer
import cats.implicits._
import scala.concurrent.Future
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.ExecutionContext
import com.kpaudel.shared.MyApi
import com.kpaudel.server.MyApiImpl
object Transport extends RequestTransport[String, Future] {
  // implement the transport layer. this example just calls the router directly.
  // in reality, the request would be sent over a connection.
  val router: Router[ByteBuffer, Future] = Router[ByteBuffer, Future].route[MyApi](MyApiImpl)
}
```

The contents of my `build.gradle` file are
```
repositories{
	maven { url "https://jitpack.io" }
}

dependencies {
	implementation'com.github.cornerman.sloth:sloth_sjs0.6_2.12:master-SNAPSHOT'
	implementation'com.github.cornerman.sloth:sloth_2.12:master-SNAPSHOT'
	// https://mvnrepository.com/artifact/me.chrons/boopickle
	compile group: 'io.suzaku', name: 'boopickle_sjs0.6_2.12', version: '1.3.0'
	compile group: 'io.suzaku', name: 'boopickle_2.12', version: '1.3.0'
}

```

**Comment by cornerman** [comment]
Hmm, the imports look good to me - that is mainly the ExecutionContext and `cats.implicits._`. Can you check whether you can just get a `Functor[Future]` implicitly without the router stuff? Like `val myFunctor = implicitly[Functor[Future]]`.

Just for reference, here is a test case that uses an API with `Future`: https://github.com/cornerman/sloth/blob/master/sloth/src/test/scala/SlothSpec.scala.

**Comment by krishna444** [comment]
I checked with
val myFunctor=implicitly

**Comment by cornerman** [comment]
> I checked with val myFunctor=implicitly

Did it work?

**Comment by cornerman** [comment]
Isolated, it works like this:

```scala
object Testing {
  import cats.implicits._ // you could try import the future implicit directly instead: import import cats.instances.future.catsStdInstancesForFuture
  import cats.Functor
  import scala.concurrent.ExecutionContext.Implicits.global
  import scala.concurrent.Future

  val functor = implicitly[Functor[Future]]
}
```

So, I guess there is some conflicting implicit in your example code. You might want to reduce your code unitil it works to find out what is causing this.

Or you can add a compiler flag to see debug output of why implicits were not chosen:

In you build.sbt:
```
scalacOptions += "-Xlog-implicits"
```

Then you can compile and search for `catsStdInstancesForFuture` in the compiler output, it should tell you why it was not chosen. For example something like this:

```
[info]       catsStdInstancesForFuture is not a valid implicit value for cats.Functor[scala.concurrent.Future] because:
[info]       hasMatchingSymbol reported error: Cannot find an implicit ExecutionContext. You might pass
[info]       an (implicit ec: ExecutionContext) parameter to your method
[info]       or import scala.concurrent.ExecutionContext.Implicits.global.
[info]       L9:  val functor = implicitly[Functor[Future]]
[info]       L9: 
```

**Comment by cornerman** [comment]
Just an idea: Are there maybe two conflicting ExecutionContexts? You can test by try to compile `implicity[ExecutionContext]`.

**Comment by krishna444** [comment]
The code you provided is working! So far I am not getting any error. Will let you know if any error  comes if I integrate into my project. Thanks a lot for your help!

**Comment by cornerman** [comment]
Great that it works now! Have fun :)

**Comment by krishna444** [comment]
It is working! It was a bit tricky to make it work :)
